apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rag-service
  namespace: default
spec:
  serviceUnhealthySecondThreshold: 1800
  deploymentUnhealthySecondThreshold: 1800
  serveConfigV2: |
    applications:
      - name: rag-service
        import_path: "rag_serve:deployment"
        route_prefix: "/"
        runtime_env:
          pip: ["sentence-transformers", "boto3>=1.34.0"]
          env_vars:
            LD_LIBRARY_PATH: "/home/ray/anaconda3/lib:$LD_LIBRARY_PATH"
            MODEL_ID: "/models/mistral-7b-v0-3"
            MODEL_ENDPOINT: "http://vllm-serve-svc:8000/v1/chat/completions"
            S3_VECTOR_BUCKET_NAME: "${S3_VECTOR_BUCKET_NAME}"
            S3_VECTOR_INDEX_NAME: "${S3_VECTOR_INDEX_NAME}"
            AWS_REGION: "${AWS_REGION}"
        deployments:
          - name: rag-service-deployment
            autoscaling_config:
              metrics_interval_s: 0.2
              min_replicas: 1
              max_replicas: 2
              look_back_period_s: 2
              downscale_delay_s: 600
              upscale_delay_s: 30
              target_num_ongoing_requests_per_replica: 5
            graceful_shutdown_timeout_s: 5
            max_concurrent_queries: 100
            ray_actor_options:
              num_cpus: 1
              num_gpus: 0
  rayClusterConfig:
    rayVersion: '2.43.0'
    enableInTreeAutoscaling: true
    headGroupSpec:
      headService:
        metadata:
          name: rag-service
          namespace: default
      rayStartParams:
        dashboard-host: '0.0.0.0'
        num-cpus: "0"
      template:
        spec:
          serviceAccountName: s3-access-sa
          containers:
          - name: ray-head
            image: public.ecr.aws/aws-containers/aiml/ray-2.43.0-py311-vllm0.7.3:latest
            imagePullPolicy: IfNotPresent
            lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh", "-c", "ray stop"]
            ports:
            - containerPort: 6379
              name: gcs
            - containerPort: 8265
              name: dashboard
            - containerPort: 10001
              name: client
            - containerPort: 8000
              name: serve
            - containerPort: 52365
              name: dashboard-agent
            volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
            - name: rag-serve-script
              mountPath: /home/ray/python/rag_serve.py
              subPath: rag_serve.py
            - name: persistent-storage
              mountPath: /models
            resources:
              limits:
                cpu: 2
                memory: "12G"
              requests:
                cpu: 2
                memory: "12G"
            env:
            - name: PYTHONPATH
              value: "/home/ray/python"
            - name: LD_LIBRARY_PATH
              value: "/home/ray/anaconda3/lib:$LD_LIBRARY_PATH"
            - name: S3_VECTOR_BUCKET_NAME
              value: "${S3_VECTOR_BUCKET_NAME}"
            - name: S3_VECTOR_INDEX_NAME
              value: "${S3_VECTOR_INDEX_NAME}"
            - name: AWS_REGION
              value: "${AWS_REGION}"
          nodeSelector:
            node.kubernetes.io/instance-type: m5.xlarge
          volumes:
          - name: ray-logs
            emptyDir: {}
          - name: rag-serve-script
            configMap:
              name: rag-serve-script
          - name: persistent-storage
            persistentVolumeClaim:
              claimName: fsx-models
    workerGroupSpecs:
    - replicas: 1
      minReplicas: 1
      maxReplicas: 2
      groupName: cpu-group
      rayStartParams: {}
      template:
        spec:
          serviceAccountName: s3-access-sa
          containers:
          - name: ray-worker
            image: public.ecr.aws/aws-containers/aiml/ray-2.43.0-py311-vllm0.7.3:latest
            imagePullPolicy: IfNotPresent
            lifecycle:
              preStop:
                exec:
                  command: ["/bin/sh", "-c", "ray stop"]
            volumeMounts:
            - mountPath: /tmp/ray
              name: ray-logs
            - name: rag-serve-script
              mountPath: /home/ray/python/rag_serve.py
              subPath: rag_serve.py
            - name: persistent-storage
              mountPath: /models
            resources:
              limits:
                cpu: 2
                memory: "2Gi"
              requests:
                cpu: 1
                memory: "2Gi"
            env:
            - name: PYTHONPATH
              value: "/home/ray/python"
            - name: LD_LIBRARY_PATH
              value: "/home/ray/anaconda3/lib:$LD_LIBRARY_PATH"
            - name: S3_VECTOR_BUCKET_NAME
              value: "${S3_VECTOR_BUCKET_NAME}"
            - name: S3_VECTOR_INDEX_NAME
              value: "${S3_VECTOR_INDEX_NAME}"
            - name: AWS_REGION
              value: "${AWS_REGION}"
          volumes:
          - name: ray-logs
            emptyDir: {}
          - name: rag-serve-script
            configMap:
              name: rag-serve-script
          - name: persistent-storage
            persistentVolumeClaim:
              claimName: fsx-models